apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ramdas1999/ems-backend:latest
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: "<POSTGRES_HOST>"
        - name: DB_USER
          value: "<POSTGRES_USER>"
        - name: DB_PASSWORD
          value: "<POSTGRES_PASSWORD>"
        - name: DB_NAME
          value: "<POSTGRES_DB_NAME>"
        - name: DB_PORT
          value: "<POSTGRES_PORT>"
        - name: ALLOWED_ORIGINS
          value: "<ALLOWED_ORIGINS>"
